### ISSUE TITLE
Отрефакторить

### ISSUE THREAD

**Issue by Evil1991** [mefist1990/pwmigrationproject#1]
https://github.com/mefist1990/pwmigrationproject/blob/d1e25d5071389bb5305dc1ef9aebdfa2c2485d28/pwmigrationproject.php#L159

Плохая практика, там один и тот же код для каждой таблицы, вынеси в функцию

**Comment by mefist1990** [comment]
Точно и с записью в файл так-же, поправлю

**Comment by mefist1990** [comment]
https://github.com/mefist1990/pwmigrationproject/commit/462e58b717ffd37837cb5ef61737263cb77b1087
