### ISSUE TITLE
Плохая практика, что товары восстанавливаются в отрыве связанных сущностей

### ISSUE THREAD

**Issue by Evil1991** [mefist1990/pwmigrationproject#2]
https://github.com/mefist1990/pwmigrationproject/blob/d1e25d5071389bb5305dc1ef9aebdfa2c2485d28/pwmigrationproject.php#L311

Может получится так, что товар восстановится, а всякие характеристики и комбинации нет, думаю лучше сразу все вместе бэкапить

**Comment by mefist1990** [comment]
Т.е. собрать все в одну большую таблицу->массив-> json и дальше занести в файл?

**Comment by mefist1990** [comment]
Перед восстановлением из БД будет сначала проводиться анализ таблиц, если они идентичны будет доступно восстановление, если нет будет выводиться предупреждение с указанием проблемных таблиц и в чем проблема (в будущем проблема будет сама решаться), только после того как человек вручную внесет корректировку в БД(добавит новые столбцы) , тогда можно будет уже восстановить данные. Это уберет ручной труд, чтобы сразу видно было, где у нас расхождение в строках
