### ISSUE TITLE
Насколько необходима данная библиотека?

### ISSUE THREAD

**Issue by Evil1991** [mefist1990/pwmigrationproject#3]
https://github.com/mefist1990/pwmigrationproject/blob/d1e25d5071389bb5305dc1ef9aebdfa2c2485d28/pwmigrationproject.php#L27

**Comment by mefist1990** [comment]
Пока работаю с ней, т.к. тестировал идею сбора данных в htm файл и она себя показала с хорошей стороны (минимальный вес и минимум памяти (xml тут проигралл + не привязывался к бд), можно маневрировать с тегами. я уже думаю , как изъять нужные фуннкции  в основное тело модуля, думаю как пойму что мне надо, перенесу в основное тело и удалю связь.

**Comment by mefist1990** [comment]
https://github.com/mefist1990/pwmigrationproject/commit/462e58b717ffd37837cb5ef61737263cb77b1087
